fr:
  languageCode: FR
  languageName: Français
  title: Miriam Lasserre
  weight: 1
  permalinks:
    ebooks: /ebooks/:year-:slug/
    expertises: /services/:slug/
    publications: /presse/:slug/

en:
  languageCode: EN
  languageName: English
  title: Miriam Lasserre
  weight: 2
  permalinks:
    ebooks: /ebooks/:year-:slug/
    expertises: /services/:slug/
    publications: /press/:slug/
