fr:
  languageCode: fr
  languageName: Français
  title: Miriam Lasserre
  weight: 1
  permalinks:
    ebooks: /ebooks/:year-:slug/
    publications: /presse/:slug/
    services: /services/:slug/

en:
  languageCode: en
  languageName: English
  title: Miriam Lasserre
  weight: 2
  permalinks:
    ebooks: /ebooks/:year-:slug/
    publications: /press/:slug/
    services: /services/:slug/
