imports:
- path: github.com/hugolify/hugolify-theme-publications
- path: github.com/hugolify/hugolify-theme-services
- path: github.com/hugolify/hugolify-theme
- path: github.com/hugolify/hugolify-admin
