imports:
- path: github.com/hugolify/hugolify-example-site
- path: github.com/hugolify/hugolify-theme-publications
- path: github.com/hugolify/hugolify-theme
- path: github.com/hugolify/hugolify-netlify-cms
